---
# makepkg compiler target (override for VMs: x86-64-v3)
makepkg_march: znver4

base_packages:
  - git
  - curl
  - wget
  - ripgrep
  - fd
  - bat
  - eza
  - fzf
  - jq
  - htop
  - btop
  - tmux
  - starship
  - tree
  - unzip
  - p7zip
  - zsh
  - zsh-completions
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - man-db
  - man-pages
  - base-devel

# Packages to explicitly remove from all machines
# Add packages here when removing them from install lists
removed_packages: []
# removed_packages:
#   - some-old-package
#   - another-unwanted-thing

user_groups:
  - wheel
  - video
  - render
  - input
