---
# CachyOS-specific settings

# Kernel
cachyos_kernel: linux-cachyos
cachyos_kernel_headers: linux-cachyos-headers

# Pacman
pacman_parallel_downloads: 10
pacman_color: true
pacman_cachyos_repos: true

# Snapper / BTRFS
snapper_config_name: root
snapper_snapshot_limit: 50
snapper_timeline_create: false
snapper_timeline_cleanup: true
